# Matrix decompositions 
Useful tool for reducing a matrix to their constituent parts in order to simplify more complex operations like computing the power of the matrix.<br>
Original matrix in which we are interested may be very 'big', sparse, with no order. Factoring it would yield a set of more manageable, compact and ordered matrices. Further, using these factors, it is easy to find hidden relationships (if any) like correlation, orthogonality, sub-space/ span/ projection in the original matrix.

## LU Matrix Decomposition
For square matrices and decomposes a matrix into triangular matrices L and U.
<br>
The LU decomposition is found using an iterative numerical process and can fail for those matrices that cannot be decomposed or decomposed easily. A variation of this decomposition that is numerically more stable to solve in practice is called the **LUP decomposition**, or the LU decomposition with partial pivoting.
<br>
In the Gaussian elimination process, when there's a zero on the pivot, we have to switch rows, which introduces a Permutation matrix P. Also, very small non-zero pivot values lead to numerical instability in a floating point environment. Basic algorithms avoid this by searching for the entry with the largest absolute value in the pivot column and switching the corresponding row with the pivot row. This switch can be expensive, so often the largest absolute value entry will have to be bigger than the pivot's absolute value by some factor, e.g. 10, for the switch to occur. This reduces the number of switches, but keeps those that would be necessary to limit floating point errors.

In [1]:
import numpy as np
from numpy import array
from scipy.linalg import lu
# define matrix
print '==========Original Matrix==========='
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

==========Original Matrix===========
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# LU decomposition
P, L, U = lu(A)
print '==========LUP Decomposition==========='
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print '\n==========Reconstructed Matrix==========='
print(B)

==========LUP Decomposition===========
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]
[[ 1.          0.          0.        ]
 [ 0.14285714  1.          0.        ]
 [ 0.57142857  0.5         1.        ]]
[[  7.00000000e+00   8.00000000e+00   9.00000000e+00]
 [  0.00000000e+00   8.57142857e-01   1.71428571e+00]
 [  0.00000000e+00   0.00000000e+00   1.11022302e-16]]

==========Reconstructed Matrix===========
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


## LDU Decomposition
Just normalize the U matrix to pull out D

In [3]:
D = np.diag(np.diag(U))   # D is just the diagonal of U
U /= np.diag(U)[:, None]  # Normalize rows of U
print '========== D & New U ==========='
print np.round(D)
print U
print '\n==========Reconstructed Matrix==========='
P.dot(L.dot(D.dot(U))) 

========== D & New U ===========
[[ 7.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[ 1.          1.14285714  1.28571429]
 [ 0.          1.          2.        ]
 [ 0.          0.          1.        ]]

==========Reconstructed Matrix===========


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

## QR Matrix Decomposition
For m x n matrices (not limited to square matrices)<br>
Q: m x m <br>
R: m x n upper triangle matrix 

NumPy qr() function: By default, the function returns the Q and R matrices with smaller or ‘reduced’ dimensions that is more economical. We can change this to return the expected sizes of m x m for Q and m x n for R by specifying the mode argument as ‘complete’

In [4]:
from numpy.linalg import qr
# define a 3x2 matrix
AA = array([[1, 2], [3, 4], [5, 6]])
print '==========Original Matrix==========='
print(AA)
# QR decomposition
Q, R = qr(AA, 'complete')
print '==========QR Decomposition==========='
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print '\n==========Reconstructed Matrix==========='
print(B)

==========Original Matrix===========
[[1 2]
 [3 4]
 [5 6]]
==========QR Decomposition===========
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

==========Reconstructed Matrix===========
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


## Cholesky Decomposition
For hermitian (square symmetric if real valued) AND positive definite matrices (all values > 0)

Lower Triangular matrix form (Numpy Default):
A = L . L^T  <br>
Upper Triangular matrix form (Scipy Default):
A = U^T . U

#### Applications: <br>
1) Used for solving normal equations for linear least squares (eg in linear regression), as well as simulation and optimization methods <br>
2) Cholesky transformation - to correlate and uncorrelate variables <br>
https://blogs.sas.com/content/iml/2012/02/08/use-the-cholesky-transformation-to-correlate-and-uncorrelate-variables.html <br>
3) Monte Carlo simulation - The correlation matrix is decomposed, to give the lower-triangular L. Applying this to a vector of uncorrelated samples u produces a sample vector Lu with the covariance properties of the system being modeled <br>
4) Kalman filters - Unscented Kalman filters commonly use the Cholesky decomposition to choose a set of so-called sigma points. The Kalman filter tracks the average state of a system as a vector x of length N and covariance as an N × N matrix P. The matrix P is always positive semi-definite and can be decomposed into LL.T. The columns of L can be added and subtracted from the mean x to form a set of 2N vectors called sigma points. These sigma points completely capture the mean and covariance of the system state. 

In [5]:
from numpy.linalg import cholesky
# define a 3x3 matrix
AAA = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print '========== Original Matrix ==========='
print(AAA)
# Numpy Cholesky decomposition: L is default
L = cholesky(AAA)
print '========== Numpy Cholesky Decomposition ==========='
print(L)
# reconstruct
B = L.dot(L.T)
print '\n==========Reconstructed Matrix==========='
print(B)

# Scipy Cholesky Decomposition: U is default 
from scipy.linalg import cholesky
U = cholesky(AAA)
print '\n========== Scipy Cholesky Decomposition ==========='
print(U)
# reconstruct
B = np.dot(U.T,U)
print '\n==========Reconstructed Matrix==========='
print(B)

========== Original Matrix ===========
[[2 1 1]
 [1 2 1]
 [1 1 2]]
========== Numpy Cholesky Decomposition ===========
[[ 1.41421356  0.          0.        ]
 [ 0.70710678  1.22474487  0.        ]
 [ 0.70710678  0.40824829  1.15470054]]

==========Reconstructed Matrix===========
[[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]

========== Scipy Cholesky Decomposition ===========
[[ 1.41421356  0.70710678  0.70710678]
 [ 0.          1.22474487  0.40824829]
 [ 0.          0.          1.15470054]]

==========Reconstructed Matrix===========
[[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]


## Non-negative matrix factorization (NMF) 
decomposes a matrix A into two matrices that have non-negative elements. (A must have non-negative elements too). NMF is suited for tasks where the underlying factors can be interpreted as non-negative.  <br>
The factorization is not unique.  <br>

https://www.siam.org/meetings/sdm11/park.pdf

#### NMF Applications
1) Dimensionality Reduction <br>
2) Text mining - Topic modeling, Documnet Clustering <br>
3) Image analysis and computer vision - Feature representation, sparse coding <br>
4) Latent feature extraction <br>
5) Social network - Community structure and trend detection, Recommendation system <br>
6) Acoustic signal processing, blind source separating <br>
7) Financial data https://www.researchgate.net/publication/228656913_Analysis_of_financial_data_using_non-negative_matrix_factorization

In [6]:
from sklearn.decomposition import NMF
A = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]
A = array(A)
print '========== Original Matrix ==========='
print(A)
nmf = NMF()
W = nmf.fit_transform(A)
print '\n========== NMF Decomposition ==========='
print W
H = nmf.components_
print H
print '\n==========Reconstructed Matrix==========='
new_A = np.dot(W,H)
print np.round(new_A)

========== Original Matrix ===========
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]

========== NMF Decomposition ===========
[[  0.00000000e+00   7.36983291e-01   1.68362443e+00   1.60383211e-01]
 [  0.00000000e+00   1.51492480e+00   0.00000000e+00   6.41010416e-03]
 [  9.04799081e-04   0.00000000e+00   5.53924595e-01   1.53101825e+00]
 [  0.00000000e+00   3.78732207e-01   0.00000000e+00   1.15003851e+00]
 [  4.68844828e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]]
[[ 0.          0.21329038  1.06645088  0.85316074]
 [ 2.64058825  0.          0.          0.64628388]
 [ 1.81306226  1.78222468  0.          0.        ]
 [ 0.          0.00519399  0.          3.26530094]]

==========Reconstructed Matrix===========
[[ 5.  3.  0.  1.]
 [ 4.  0.  0.  1.]
 [ 1.  1.  0.  5.]
 [ 1.  0.  0.  4.]
 [ 0.  1.  5.  4.]]


#### Topic Modeling with NMF
Displays the top words in a topic. Topics are not labeled by the algorithm — a numeric index is assigned.

NMF has an inherent clustering property, such that W and H represent the following information about A:

A (Document-word matrix) — input that contains which words appear in which documents.

W (Basis vectors) — the topics (clusters) discovered from the documents.

H (Coefficient matrix) — the membership weights for the topics in each document.

Another interesting property of NMF is that it naturally produces sparse representations. This makes sense in the case of topic modeling: documents generally do not contain a large number of topics.

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer#, CountVectorizer
from sklearn.datasets import fetch_20newsgroups

dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
documents = dataset.data

no_features = 1000

tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, max_features=no_features, stop_words='english')
tfidf = tfidf_vectorizer.fit_transform(documents)
tfidf_feature_names = tfidf_vectorizer.get_feature_names()

no_topics = 20
# Run NMF
nmf = NMF(n_components=no_topics, random_state=1, alpha=.1, l1_ratio=.5, init='nndsvd').fit(tfidf)

no_top_words = 10
for topic_idx, topic in enumerate(nmf.components_):
    topic_str = " ".join([tfidf_feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]])
    print "Topic %d:%s" % (topic_idx+1, topic_str)

Topic 1:people time right did good said say make way government
Topic 2:window problem using server application screen display motif manager running
Topic 3:god jesus bible christ faith believe christian christians sin church
Topic 4:game team year games season players play hockey win league
Topic 5:new 00 sale 10 price offer shipping condition 20 15
Topic 6:thanks mail advance hi looking info help information address appreciated
Topic 7:windows file files dos program version ftp ms directory running
Topic 8:edu soon cs university ftp internet article email pub david
Topic 9:key chip clipper encryption keys escrow government public algorithm nsa
Topic 10:drive scsi drives hard disk ide floppy controller cd mac
Topic 11:just ll thought tell oh little fine work wanted mean
Topic 12:does know anybody mean work say doesn help exist program
Topic 13:card video monitor cards drivers bus vga driver color memory
Topic 14:like sounds looks look bike sound lot things really thing
Topic 15:don kn

#### Non-convexity
NMF algo is known be non-convex and NP-hard. So, it may have difficulty with convergence and stability. <br>
One approach to tackle this is using SVD initialization (NNDSVD) <br>

https://calculatedcontent.com/2013/05/06/advances-in-convex-nmf-part-1-linear-programming/

## Spectral (Eigen) Decomposition
Eigendecomposition is a type of decomposition that involves decomposing a **square** matrix into a set of eigenvectors and eigenvalues. This can help us to analyze certain properties of the matrix, much as decomposing an integer into its prime factors can help us understand the behavior of that integer.

A matrix could have one eigenvector and eigenvalue for each dimension of the parent matrix. Not all square matrices can be decomposed. The parent matrix can be shown to be a product of the eigenvectors and eigenvalues.

A vector is an eigenvector of a matrix if it satisfies the following equation
A . v = lambda . v

A = Q . diag(V) . Q^-1

Where Q is a matrix comprised of the eigenvectors, diag(V) is a diagonal matrix comprised of the eigenvalues along the diagonal (sometimes represented with a capital lambda), and Q^-1 is the inverse of the matrix comprised of the eigenvectors.

Eigenvalues are coefficients applied to eigenvectors that give the vectors their length or magnitude. For example, a negative eigenvalue may reverse the direction of the eigenvector as part of scaling it. A matrix that has only positive eigenvalues is referred to as a _positive definite matrix_, whereas if the eigenvalues are all negative, it is referred to as a _negative definite matrix_.

Eigenvectors returned by software packages are unit vectors (i.e. their length or magnitude is equal to 1.0). They are often referred as right vectors, which simply means a column vector (as opposed to a row vector or a left vector).


In [8]:
# eigendecomposition
from numpy.linalg import eig
print '========== Original Matrix ==========='
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print A
# calculate eigendecomposition
values, vectors = eig(A)
print '\n========== Eigen Values ==========='
print(values)
print '\n========== Orthonormal Eigen Vectors ==========='
print(vectors)
# Reconstruct Original Matrix given only the eigenvectors and eigenvalues
print '\n==========Reconstructed Matrix==========='
from numpy import diag, dot
from numpy.linalg import inv 

# create diagonal matrix from eigenvalues. (The eigenvalues need to be arranged into a diagonal matrix)
L = diag(values)
# reconstruct the original matrix
B = vectors.dot(L).dot(inv(vectors))
print(B)

========== Original Matrix ===========
[[1 2 3]
 [4 5 6]
 [7 8 9]]

========== Eigen Values ===========
[  1.61168440e+01  -1.11684397e+00  -1.30367773e-15]

========== Orthonormal Eigen Vectors ===========
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

==========Reconstructed Matrix===========
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


**Covariance matrix** is a square and symmetric matrix that summarises the variance between two variables. 
Eigenvectors with the largest eigenvalue of a covariance matrix gives the direction along which the data has the largest variance.

#### Eigen decomposition vs singular value decomposition
In an eigen-decomposition, A can be represented by a product of its eigenvectors Q and diagonalised eigenvalues Λ:<br> <br>
A=QΛ(Q^−1) 
<br> <br>
--Unlike an eigen-decomposition where the matrix must be square (n×n), SVD can decompose a matrix of any dimension.<br>
--Column vectors in Q are not always orthogonal so the change in basis is not a simple rotation. U and V are orthogonal and always represent rotations (and reflections).<br>
--Singular values in S are all real and non-negative. The eigenvalues in Λ can be complex and have imaginary numbers.

### Practical Applications
1) Using SVD for image compression.<br>
Checkout: https://github.com/abhi25t/machine_learning/blob/master/SVD.ipynb

2) **Dimensionality Reduction/PCA** The principal components correspond the the largest eigenvalues of A'A and this yields the least squared projection onto a smaller dimensional hyperplane, and the eigenvectors become the axes of the hyperplane. Dimensionality reduction is extremely useful in machine learning and data analysis as it allows one to understand where most of the variation in the data comes from.

3) **Low rank factorization for collaborative prediction** This what Netflix does (or once did) to predict what rating you'll have for a movie you have not yet watched. It uses the SVD, and throws away the smallest eigenvalues of A'A.

4) **The Google Page Rank algorithm** The largest eigenvector of the graph of the internet is how the pages are ranked.

5) **Spectral clustering** - It makes use of the spectrum (eigenvalues) of the similarity matrix of the data to perform dimensionality reduction before clustering in fewer dimensions. <br>
The goal of spectral clustering is to cluster data that is connected but not necessarily compact or clustered within convex boundaries. <br> The power of Spectral Clustering is to identify non-compact clusters in  a single data set. <br>
Checkout: https://github.com/abhi25t/machine_learning/blob/master/Spectral_Clustering.ipynb

Good Read

Section 2.7 Eigendecomposition [Deep Learning (Ian Goodfellow, Yoshua Bengio, Aaron Courville)]

3Blue1Brown - A visual understanding of eigenvectors, eigenvalues
https://www.youtube.com/watch?v=PFDu9oVAE-g

To check Complex topics: <br>
https://calculatedcontent.com/2012/09/09/dimensional-reduction-via-an-effective-operator-kernel/ <br>
https://calculatedcontent.com/2012/09/20/effective-operators-for-eigenvalues-and-clustering/ <br>
https://calculatedcontent.com/2012/09/21/eigenvalue-independent-effective-semantic-operator/ <br>

Matrix multiplication meaning:
http://alyssaq.github.io/2015/visualising-matrices-and-affine-transformations-with-python/